language: ruby
bundler_args: --without production
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
rvm:
  - "2.0.0"
  - "2.1.0"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - cp config/database.yml.travis config/database.yml

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
