development:
  facebook_key: "620958307990688"
  facebook_secret: "03be09569acb47ba61176e37c6c9b052"

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

production:
  facebook_key: "620958307990688"
  facebook_secret: "03be09569acb47ba61176e37c6c9b052"

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"